The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) nvidia/.latest   2) slurm/.latest
/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/utils/generic.py:311: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/utils/generic.py:311: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/utils/generic.py:311: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/peft/tuners/lora.py:475: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(
/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:166: UserWarning: You didn't pass a `max_seq_length` argument to the SFTTrainer, this will default to 1024
  warnings.warn(
Map:   0%|          | 0/10000 [00:00<?, ? examples/s]Map:  10%|█         | 1000/10000 [00:00<00:01, 6449.46 examples/s]Map:  30%|███       | 3000/10000 [00:00<00:00, 9349.56 examples/s]Map:  40%|████      | 4000/10000 [00:00<00:00, 9006.21 examples/s]Map:  60%|██████    | 6000/10000 [00:00<00:00, 9693.47 examples/s]Map:  80%|████████  | 8000/10000 [00:00<00:00, 9545.70 examples/s]Map:  90%|█████████ | 9000/10000 [00:00<00:00, 9484.50 examples/s]Map: 100%|██████████| 10000/10000 [00:01<00:00, 9468.35 examples/s]Map: 100%|██████████| 10000/10000 [00:01<00:00, 9300.30 examples/s]
Map:   0%|          | 0/1000 [00:00<?, ? examples/s]Map: 100%|██████████| 1000/1000 [00:00<00:00, 11182.51 examples/s]
Traceback (most recent call last):
  File "/fred/oz413/ANeurIPS2024_SPV-MIA/./ft_llms/llms_finetune.py", line 259, in <module>
    trainer = SFTTrainer(
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 212, in __init__
    super().__init__(
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/trainer.py", line 557, in __init__
    self.callback_handler = CallbackHandler(
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/trainer_callback.py", line 305, in __init__
    self.add_callback(cb)
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/trainer_callback.py", line 322, in add_callback
    cb = callback() if isinstance(callback, type) else callback
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/transformers/integrations/integration_utils.py", line 673, in __init__
    raise RuntimeError("WandbCallback requires wandb to be installed. Run `pip install wandb`.")
RuntimeError: WandbCallback requires wandb to be installed. Run `pip install wandb`.
Traceback (most recent call last):
  File "/fred/oz413/.conda/envs/llm-env/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/fred/oz413/.conda/envs/llm-env/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/fred/oz413/.conda/envs/llm-env/bin/python', './ft_llms/llms_finetune.py', '--output_dir', './ft_llms/gpt2-xl/ag_news/baseline/', '--block_size', '128', '--eval_steps', '100', '--save_epochs', '100', '--log_steps', '100', '-d', 'ag_news', '-m', 'gpt2-xl', '--packing', '--use_dataset_cache', '-e', '2', '-b', '4', '-lr', '5e-5', '--gradient_accumulation_steps', '1', '--train_sta_idx=0', '--train_end_idx=10000', '--eval_sta_idx=0', '--eval_end_idx=1000', '--dataset_config_name', 'default']' returned non-zero exit status 1.
